# ======================================================================
# 19 Jekyll yapılandırması
# ======================================================================

# kalıcı adresler (lütfen bu ayara dokunmayın)
permalink: /:categories:title

# sözdizimi renklendirmesi
pygments: true

# ----------------------------------------------------------------------
# temel parametreler
# 
# bu parameterleri doğrudan "site" uzayına yerleştiriyoruz
# ----------------------------------------------------------------------

# github hesap adı (ör. roktas)
account: "00010011"

# github organizasyonu (ör. 19)
organization: 19

# bu siteyi üreten github deposu (ör. roktas.github.com)
repository: ben

# üretilen sitenin web adresi ne?  ör. "http://foo.github.com/bar".
url: http://00010011.github.com/ben

# sitede kullanılan css, görsel, javascript gibi kaynaklar
# için kullanılacak "dijital varlıklar" adresi.
# dikkat!  bu adresi mutlak formda tanımlayın.  örnekler:
#
# 	/assets
# 	http://roktas.github.com/assets
assets: http://00010011.github.com/assets

# ----------------------------------------------------------------------
# site parametreleri
# 
# kalan tüm parameterleri "site.param" uzayına koyuyoruz
# ----------------------------------------------------------------------
param:
        # --------------------------------------------------------------
        # kişisel parametreler
        # --------------------------------------------------------------
        # kısa kullanıcı adı (ör. roktas)
        # dikkat!  sisteminizdeki ad github hesabından farklı olabilir
        name: roktas
        # tam kullanıcı adı (ör. Recai Oktaş)
        fullname: 19 Jekyll Şablonu
        # email adresi (ör. roktas@bil.omu.edu.tr)
        email: 19@bil.omu.edu.tr
        # sitede kullanılacak tepe web adresi (ör. http://roktas.me)
        # dikkat!  bu değişkeni "url" ile karıştırmayın!
        web: http://00010011.github.com
        # ünvan (ör. Bilgisayar Mühendisliği Öğrencisi)
        title: <a href="http://ondokuz.biz/">19</a> üyesi
        # GnuPG kısa parmak izi (ör. DEADBEEF)
        gpg: DEADBEEF
        # twitter adresi (ör. http://19.statusnet/roktas)
        twitter: http://19.status.net
        # flick adresi (ör. http://flickr.com/photos/roktas)
        flickr: http://flickr.com/photos/19
        # facebook adresi (ör. http://facebook.com/roktas)
        facebook: http://www.facebook.com/#!/group.php?gid=101297483252537
        # özet akışı adresi (ör. http://feeds.feedburner.com/roktas)
        feed: http://feeds.feedburner.com/19

        # --------------------------------------------------------------
        # ekstra özellik parametreleri
        #
        # bu değişkenler tanımlanmazsa (~ kullanın) öntanımlı sitede
        # ilgili özellik bulunmayacaktır (örneğin: disqus)
        #
        # dikkat!  değişkenin tanımlı olmaması için ~ değeri verin
        # --------------------------------------------------------------
        # logo (ör. http://00010011.github.com/assets/19/19-normal-128x128.png)
        logo: http://00010011.github.com/assets/19/19-normal-128x128.png
        # google analytics takip numarası (ör. UA-1234567-8
        googleanalyticsid: ~
        # sayfa yorumları için disqus site kaydı (ör. roktas)
        disqus: ~
        # GitHub şerit metni (ör. GitHub'dayım)
        ribbon: GitHub'dayım

        # --------------------------------------------------------------
        # bölüm seçme parametreleri
        #
        # dikkat!  çok fazla bölüm atlamayı tavsiye etmiyoruz
        # --------------------------------------------------------------
        # 0'ncı bölümü atla
        # nouse0: 1
        # 1'nci bölümü atla
        # nouse1: 1
        # 2'nci bölümü atla
        nouse2: 1
        # 7'nci bölümü atla
        nouse7: 1
        # 9'ncu bölümü atla
        # nouse9: 1
